name: Publish Test Report to Github Pages
description: "Publish the Test Report to the Github Pages"

outputs:
  page_url:
    description: "Test Report Github page"
    value: ${{ steps.publish.outputs.page_url }}

runs:
  using: "composite"

  steps:
    - name: Prepare Javadocs and Test Report for Github Pages
      shell: bash
      run: |
        scp -r target/site/apidocs github-pages/javadocs
        scp test-results/TestExecutionReport.html github-pages/TestExecutionReport.html

    - name: Setup Github Pages
      uses: actions/configure-pages@v2

    - name: Upload Test execution Extent Report HTML to Github Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: "github-pages/"

    - name: Publish HTML Report to Github Pages
      id: publish
      uses: actions/deploy-pages@v1